import type * as Battles2 from '../models/battles2';

import { json } from '../utils';

/**
 * A list of current Hall of Masters events
 */
export function homs() {
  return json<Battles2.Hom[]>(`/battles2/homs`);
}

/**
 * A HOM leaderboard
 */
export function homLeaderboard({
  homID
}: {
  /** The current HoM season ID */
  homID: string;
}) {
  return json<Battles2.HomLeaderboard[]>(`/battles2/homs/${homID}/leaderboard`);
}

/**
 * Information about a Battles 2 Player
 */
export function user({
  userID
}: {
  /** This can be an encrypted ID generated by the API or a user Open Access Key (OAK) - https://ninja.kiwi/opendatafaq */
  userID: string;
}) {
  return json<Battles2.UserProfile>(`/battles2/users/${userID}`);
}

/**
 * Recent match information
 */
export function userMatches({
  userID
}: {
  /** This can be an encrypted ID generated by the API or a user Open Access Key (OAK) - https://ninja.kiwi/opendatafaq */
  userID: string;
}) {
  return json<Battles2.UserMatch[]>(`/battles2/users/${userID}/matches`);
}

/**
 * Recent hall of masters positions
 */
export function userHoms({
  userID
}: {
  /** This can be an encrypted ID generated by the API or a user Open Access Key (OAK) - https://ninja.kiwi/opendatafaq */
  userID: string;
}) {
  return json<Battles2.UserHomRank[]>(`/battles2/users/${userID}/matches`);
}
